### PR TITLE
fix: use import type where possible

### PR DESCRIPTION
**Pull request by fubhy**
Ran into this while tightening our typescript config and type validation.

### CODE REVIEW

**Comment by katspaugh** [comment]
Looks good, thank you @fubhy! Do you by any chance know if there's a way to make the IDE auto-import use the `type` keyword?

**Comment by katspaugh** [comment]
Looks like some tests are failing due to some changes in our infra. Will be fixed in #92.

**Review by katspaugh — APPROVED** [review]

**Comment by fubhy** [comment]
> Looks good, thank you @fubhy! Do you by any chance know if there's a way to make the IDE auto-import use the `type` keyword?

Yeah, there's eslinting config you could leverage using [@typescript](https://github.com/typescript-eslint/typescript-eslint) see https://typescript-eslint.io/rules/ 

Also support auto fixing with `--fix`

**Comment by fubhy** [comment]
Ah, you already got typescript-eslitn configured... 

This is the rule then: '@typescript-eslint/consistent-type-imports': 'error',

**Comment by fubhy** [comment]
https://typescript-eslint.io/rules/consistent-type-imports

**Comment by katspaugh** [comment]
Gotcha, thanks!

**Pull request merged**
